POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "ruivas",
    "description": "ruivas",
    "duration" : 690
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/7
Content-Type: application/json

{
    "title": "video 9999",
    "description": "descrição do meu vídeo 9999",
    "duration" : 9999
}

###

DELETE http://localhost:3333/videos/8